spring:
  application:
    name: product-service
  profiles:
    active: localhost
  main:
    allow-bean-definition-overriding: true
info:
  component: Prduct Service

server:
  port: 8089

logging:
  level:
    root: off
   com.alfa: DEBUG
---
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/stock_product
    password: '12345'
  jpa:
    database: postgresql
    show-sql: 'true'
    hibernate:
      ddl-auto: update


#
##spring.jpa.database=postgresql
##spring.jpa.show-sql=true
##spring.jpa.hibernate.ddl-auto=update
##spring.datasource.driver-class-name=org.postgresql.Driver
##spring.datasource.url=jdbc:postgresql://localhost:5432/stock_product
##!<--Credencales base de datos-->
##spring.datasource.username=postgres
##spring.datasource.password=12345
##
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/stock_product
#    username: postgres
#    password: 12345
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#spring:
#  profiles: localhost
#  cloud:
#    config:
#      uri: http://localhost:8888
#  jpa:
#    database: postgresql
#    hibernate:
#      show-sql: true
#      ddl-auto: create-drop
#      database-platform: org.hibernate.dialect.postgresqldialect
#    properties:
#      hibernate:
#        default_schema: stock_management
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: "jdbc:postgresql://localhost:5432/stock_management"
#    username: postgres
#    password: 12345







